config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    # Define the search route before the resources block to ensure it's matched first
    get 'products/search', to: 'products#search'
    resources :products do
      post 'like', on: :member
      get 'bundles', on: :member
    end
    resources :users do
      collection do
        get 'find_by_email', to: 'users#find_by_email' 
      end
    end
    resources :bundles
    # Catchall must be last
    get '/', to: 'home#index', as: 'home'
  end
  root 'application#react_app'
  # Health check route
  get '/up', to: 'rails/health#show', as: :rails_health_check
  # Catch-all route for React Router (must be last route in this file)
  get '*path', to: 'application#react_app'
end

app/controllers/api/home_controller.rb
module Api
  class HomeController < ApplicationController
    layout 'api'
    def index
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Demo', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Products (Backend)", api_products_path, class:"nav-link" %>
        </li>
      </ul>
      </div>
  </div>
</nav>